dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
sudo: required
before_install:
  - sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start  
install: npm install && cd dapp && npm install && cd ..
script:
- npm run test-dapp
- npm run test
